#
# load-grunt-config aliases
#
# These tasks will be available when appData.type == standalone


build:
  # required, cleans dist/ folder
  - 'clean:dist'
  # - 'fetchJson:fetchSomeApi'
  # - 'ngtemplates' # for angular app with partials, check the src for paths config
  # - 'ngAnnotate' # for angular app, check the source
  # svgstore creation
  - 'svgstore:dist'
  # copy relevant files from app/ to public/
  - 'copy:dist'
  # run useminPrepare on app/index.html
  - 'useminPrepare'
  # concat css and js files
  - 'concat:generated'
  # run postcss on concat css file
  - 'postcss'
  # minify css ( with sourcemaps )
  - 'cssmin:generated'
  # minify js ( with sourcemaps )
  - 'uglify:generated'
  # ref files inside public/
  - 'filerev:dist'
  # perform useming
  - 'usemin'
  # process public/index.html
  - 'processhtml'
  # - 'svg_injectr:multi'
  # minify public/index.html
  - 'htmlmin:single'
  # creates json from csv inside resources/locales
  - 'CsvToL10nJson:dist'
  # clean .tmp folder, comment for easier debug
  - 'clean:tmp'


dev:
  - 'clean:dev'
  # - 'svgstore:dev'
  # - 'CsvToL10nJson:dev'
  - 'browserSync:dev'
